version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_PASSWORD=pword
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5